branch-defaults:
  master:
    environment: testSwap
global:
  application_name: swap-space
  branch: null
  default_ec2_keyname: swap-space
  default_platform: Ruby 2.5 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
